import Link from "next/link";
import { Coins } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#060606] text-white">
      <header className="sticky top-0 z-50 bg-[#0a0a0a]/80 border-b border-zinc-900 backdrop-blur-md">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-tr from-emerald-600 to-emerald-400 rounded-lg flex items-center justify-center">
              <Coins className="w-4 h-4 text-black" />
            </div>
            <span className="text-lg font-black bg-clip-text text-transparent bg-gradient-to-r from-white to-emerald-400">TapCash</span>
          </Link>
          <Link href="/" className="text-zinc-500 hover:text-white text-sm font-semibold transition">← Back</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-16 space-y-10">
        <div>
          <p className="text-xs font-bold text-emerald-400 uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-4xl font-black tracking-tight">Privacy Policy</h1>
          <p className="text-zinc-500 text-sm mt-2">Last updated: May 28, 2026</p>
        </div>

        {[
          { title: "1. Information We Collect", body: `We collect information you provide directly (name, email address, payment details), information generated by your use of the Service (offer completions, click logs, transaction history, IP addresses, device identifiers, user agent), and information from third-party offer providers that facilitates reward crediting (offer ID, completion status, payout amounts).` },
          { title: "2. How We Use Your Information", body: `We use collected information to: operate and improve the Service; process and verify reward claims; detect and prevent fraud; communicate with you about your account and the Service; comply with legal obligations; and analyze usage patterns to improve user experience. We do not sell your personal information to third parties.` },
          { title: "3. Sharing of Information", body: `We share your information with: (a) offer providers and advertising networks to facilitate offer completions and verify rewards (they receive a user identifier and completion data); (b) payment processors to facilitate payouts (PayPal, gift card providers); (c) service providers who assist in operating the Service under strict confidentiality; (d) law enforcement or other parties when required by law.` },
          { title: "4. Cookies and Tracking", body: `We use cookies and similar tracking technologies to maintain your session, remember preferences, and analyze usage. Third-party offer providers may set their own cookies when you interact with their offers. You may disable cookies in your browser settings, but this may affect Service functionality.` },
          { title: "5. Data Retention", body: `We retain your account data for as long as your account is active and for a reasonable period thereafter to comply with legal obligations and resolve disputes. Fraud-related logs may be retained for up to 7 years. Transaction records are retained for at least 5 years for accounting and tax purposes.` },
          { title: "6. Security", body: `We implement industry-standard security measures including encryption in transit (TLS), encrypted storage of sensitive data, and access controls. However, no transmission over the internet is 100% secure. You are responsible for maintaining the security of your account credentials.` },
          { title: "7. Your Rights", body: `Depending on your jurisdiction, you may have the right to: access, correct, or delete your personal information; object to or restrict certain processing; data portability; and withdraw consent where processing is based on consent. To exercise these rights, contact privacy@tapcash.io. We will respond within 30 days.` },
          { title: "8. Children's Privacy", body: `TapCash is not intended for users under 18 years of age. We do not knowingly collect personal information from children. If we become aware that a child has provided us with personal information, we will take steps to delete it promptly.` },
          { title: "9. International Users", body: `TapCash is operated from the United States. If you are accessing the Service from outside the US, your information may be transferred to and processed in the US, where data protection laws may differ from those in your country.` },
          { title: "10. Changes to This Policy", body: `We may update this Privacy Policy from time to time. Material changes will be communicated via email or a prominent notice on the Service. Your continued use after changes constitutes acceptance of the updated policy.` },
          { title: "11. Contact Us", body: `For privacy-related questions or to exercise your rights, contact our Privacy team at privacy@tapcash.io.` },
        ].map(({ title, body }) => (
          <section key={title} className="space-y-2">
            <h2 className="text-lg font-bold text-white">{title}</h2>
            <p className="text-zinc-400 text-sm leading-relaxed">{body}</p>
          </section>
        ))}
      </main>

      <footer className="border-t border-zinc-900 py-8 text-center text-xs text-zinc-700">
        © {new Date().getFullYear()} TapCash · <Link href="/terms" className="hover:text-emerald-500 transition">Terms of Service</Link>
      </footer>
    </div>
  );
}
